apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demojam-gateway-zqnz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demojam-gateway-zqnz
    app.kubernetes.io/part-of: third-app
  name: demojam-gateway-zqnz
  namespace: phayes1-tenant
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: demojam-gateway-zqnz
    weight: null
status: {}
