apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demojam-gateway-zqnz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demojam-gateway-zqnz
    app.kubernetes.io/part-of: third-app
  name: demojam-gateway-zqnz
  namespace: phayes1-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: demojam-gateway-zqnz
status:
  loadBalancer: {}
